import type { FuelStation, FleetTruck, Transaction, SocialPost, FuelConsumptionPoint } from './types'

export const BRAND = {
  name: 'TswanaFuel',
  tagline: 'Preferred Energy Supplier in the SADC Region',
  established: 2011,
  group: 'LSB Group of Companies',
  website: 'https://www.lsb-tswanafuel.com',
  phone: '+267 76 552 333',
  email: 'dickson.tswanafuel@lsb.co.bw',
  totalStorageLitres: 2_000_000,
  totalSites: 9,
} as const

export const STATIONS: FuelStation[] = [
  {
    id: 'gaborone-b3',
    name: 'Gaborone Block 3',
    location: 'Gaborone, Botswana',
    lat: -24.628, lng: 25.923,
    status: 'operational',
    capacityLitres: 415_000,
    nozzles: [{ type: 'D50', count: 6 }],
    amenities: [
      { id: 'wifi', label: 'Free Wi-Fi', icon: 'wifi' },
      { id: 'security', label: '24hr Security', icon: 'shield' },
      { id: 'parking', label: 'Secure Parking', icon: 'car' },
    ],
    manager: { name: 'Thabo Molefe', phone: '+267 71 234 567', email: 'gaborone@lsb.co.bw' },
    fuelPrices: [
      { type: 'Diesel', pricePula: 11.84, lastUpdated: '2026-06-10' },
      { type: 'ULP95', pricePula: 12.20, lastUpdated: '2026-06-10' },
    ],
    operatingHours: '24/7',
  },
  {
    id: 'tlokweng',
    name: 'Tlokweng',
    location: 'Tlokweng, Botswana',
    lat: -24.653, lng: 25.975,
    status: 'operational',
    capacityLitres: 664_000,
    nozzles: [{ type: 'D50', count: 8 }],
    amenities: [
      { id: 'wifi', label: 'Free Wi-Fi', icon: 'wifi' },
      { id: 'security', label: '24hr Security', icon: 'shield' },
      { id: 'meals', label: 'Meals Available', icon: 'utensils' },
      { id: 'border', label: 'Border Permits', icon: 'file-text' },
    ],
    manager: { name: 'Kabo Setshwaelo', phone: '+267 73 456 789', email: 'tlokweng@lsb.co.bw' },
    fuelPrices: [
      { type: 'Diesel', pricePula: 11.84, lastUpdated: '2026-06-10' },
    ],
    operatingHours: '24/7',
  },
  {
    id: 'lobatse',
    name: 'Lobatse',
    location: 'Lobatse, Botswana',
    lat: -25.227, lng: 25.667,
    status: 'operational',
    capacityLitres: 480_000,
    nozzles: [{ type: 'D50', count: 8 }],
    amenities: [
      { id: 'security', label: '24hr Security', icon: 'shield' },
      { id: 'assistance', label: 'Roadside Assist', icon: 'wrench' },
    ],
    manager: { name: 'Mpho Gaobotse', phone: '+267 74 567 890', email: 'lobatse@lsb.co.bw' },
    fuelPrices: [{ type: 'Diesel', pricePula: 11.84, lastUpdated: '2026-06-10' }],
    operatingHours: '06:00 – 22:00',
  },
  {
    id: 'kazungula',
    name: 'Kazungula',
    location: 'Kazungula, Botswana',
    lat: -17.792, lng: 25.270,
    status: 'operational',
    capacityLitres: 500_000,
    nozzles: [{ type: 'D50', count: 8 }],
    amenities: [
      { id: 'wifi', label: 'Free Wi-Fi', icon: 'wifi' },
      { id: 'security', label: '24hr Security', icon: 'shield' },
      { id: 'border', label: 'Border Permits', icon: 'file-text' },
      { id: 'toll', label: 'Kazungula Bridge Toll', icon: 'bridge' },
    ],
    manager: { name: 'Didi Nkosi', phone: '+267 76 678 901', email: 'kazungula@lsb.co.bw' },
    fuelPrices: [{ type: 'Diesel', pricePula: 11.84, lastUpdated: '2026-06-10' }],
    operatingHours: '24/7',
  },
  {
    id: 'ghanzi',
    name: 'Ghanzi',
    location: 'Ghanzi, Botswana',
    lat: -21.694, lng: 21.648,
    status: 'operational',
    capacityLitres: 138_000,
    nozzles: [{ type: 'D50', count: 6 }, { type: 'ULP95', count: 8 }],
    amenities: [
      { id: 'security', label: '24hr Security', icon: 'shield' },
      { id: 'assistance', label: 'Roadside Assist', icon: 'wrench' },
    ],
    manager: { name: 'Sekhutlhe Tau', phone: '+267 72 789 012', email: 'ghanzi@lsb.co.bw' },
    fuelPrices: [
      { type: 'Diesel', pricePula: 11.84, lastUpdated: '2026-06-10' },
      { type: 'ULP95', pricePula: 12.20, lastUpdated: '2026-06-10' },
    ],
    operatingHours: '06:00 – 22:00',
  },
  {
    id: 'mamuno',
    name: 'Mamuno',
    location: 'Mamuno Border, Botswana',
    lat: -22.183, lng: 19.917,
    status: 'operational',
    capacityLitres: 184_000,
    nozzles: [{ type: 'D50', count: 6 }],
    amenities: [
      { id: 'border', label: 'Border Permits', icon: 'file-text' },
      { id: 'security', label: '24hr Security', icon: 'shield' },
    ],
    manager: { name: 'Tshiamo Kgosi', phone: '+267 71 890 123', email: 'mamuno@lsb.co.bw' },
    fuelPrices: [{ type: 'Diesel', pricePula: 11.84, lastUpdated: '2026-06-10' }],
    operatingHours: '06:00 – 20:00',
  },
  {
    id: 'francistown',
    name: 'Francistown',
    location: 'Francistown, Botswana',
    lat: -21.170, lng: 27.507,
    status: 'operational',
    capacityLitres: 92_000,
    nozzles: [{ type: 'D50', count: 4 }],
    amenities: [
      { id: 'security', label: '24hr Security', icon: 'shield' },
      { id: 'parking', label: 'Secure Parking', icon: 'car' },
    ],
    manager: { name: 'Bofelo Letsebe', phone: '+267 73 901 234', email: 'francistown@lsb.co.bw' },
    fuelPrices: [{ type: 'Diesel', pricePula: 11.84, lastUpdated: '2026-06-10' }],
    operatingHours: '06:00 – 22:00',
  },
  {
    id: 'sherwood',
    name: 'Sherwood',
    location: 'Sherwood, Botswana',
    lat: -21.765, lng: 27.467,
    status: 'operational',
    capacityLitres: 332_000,
    nozzles: [{ type: 'D50', count: 10 }],
    amenities: [
      { id: 'wifi', label: 'Free Wi-Fi', icon: 'wifi' },
      { id: 'security', label: '24hr Security', icon: 'shield' },
      { id: 'meals', label: 'Meals Available', icon: 'utensils' },
    ],
    manager: { name: 'Neo Sithole', phone: '+267 77 012 345', email: 'sherwood@lsb.co.bw' },
    fuelPrices: [{ type: 'Diesel', pricePula: 11.84, lastUpdated: '2026-06-10' }],
    operatingHours: '24/7',
  },
  {
    id: 'palapye',
    name: 'Palapye',
    location: 'Palapye, Botswana',
    lat: -22.553, lng: 27.132,
    status: 'coming_soon',
    capacityLitres: 158_000,
    nozzles: [],
    amenities: [],
    manager: { name: 'TBA', phone: '', email: '' },
    fuelPrices: [],
    operatingHours: 'Coming Soon',
  },
]

export const MOCK_FLEET: FleetTruck[] = [
  {
    id: 'tf-001',
    plateNumber: 'BG 1234 TF',
    driverName: 'Lesego Moremi',
    status: 'in_transit',
    currentLocation: { lat: -23.9, lng: 26.1, address: 'A1 Highway, near Mochudi' },
    destination: 'Tlokweng',
    fuelLevelPct: 72,
    speedKph: 85,
    loadLitres: 28_000,
    maxLoadLitres: 34_000,
    lastUpdated: new Date().toISOString(),
    route: [[-24.1, 26.4], [-23.9, 26.1], [-24.6, 26.0]],
  },
  {
    id: 'tf-002',
    plateNumber: 'BG 5678 TF',
    driverName: 'Onkabetse Seheri',
    status: 'fueling',
    currentLocation: { lat: -24.628, lng: 25.923, address: 'TswanaFuel Gaborone Block 3' },
    destination: 'Lobatse',
    fuelLevelPct: 95,
    speedKph: 0,
    loadLitres: 34_000,
    maxLoadLitres: 34_000,
    lastUpdated: new Date().toISOString(),
    route: [],
  },
  {
    id: 'tf-003',
    plateNumber: 'BG 9012 TF',
    driverName: 'Kagiso Banda',
    status: 'in_transit',
    currentLocation: { lat: -20.5, lng: 26.8, address: 'A3 Highway, Tonota' },
    destination: 'Francistown',
    fuelLevelPct: 48,
    speedKph: 92,
    loadLitres: 22_000,
    maxLoadLitres: 34_000,
    lastUpdated: new Date().toISOString(),
    route: [[-20.5, 26.8], [-21.1, 27.4]],
  },
  {
    id: 'tf-004',
    plateNumber: 'BG 3456 TF',
    driverName: 'Tumelo Ntshiwa',
    status: 'idle',
    currentLocation: { lat: -25.1, lng: 25.7, address: 'Lobatse Depot' },
    destination: '—',
    fuelLevelPct: 61,
    speedKph: 0,
    loadLitres: 0,
    maxLoadLitres: 34_000,
    lastUpdated: new Date().toISOString(),
    route: [],
  },
  {
    id: 'tf-005',
    plateNumber: 'BG 7890 TF',
    driverName: 'Boipelo Kefilwe',
    status: 'in_transit',
    currentLocation: { lat: -17.9, lng: 25.2, address: 'Near Kasane' },
    destination: 'Kazungula',
    fuelLevelPct: 30,
    speedKph: 78,
    loadLitres: 30_000,
    maxLoadLitres: 34_000,
    lastUpdated: new Date().toISOString(),
    route: [[-17.9, 25.2], [-17.79, 25.27]],
  },
]

export const MOCK_TRANSACTIONS: Transaction[] = [
  { id: 'tx-001', truckId: 'tf-001', plateNumber: 'BG 1234 TF', driverName: 'Lesego Moremi', stationId: 'gaborone-b3', stationName: 'Gaborone Block 3', fuelType: 'Diesel', litresFuelled: 480, totalPula: 5_683.2, pricePerLitre: 11.84, timestamp: '2026-06-12T07:14:00Z', rfidTag: 'RFID-TF001-A', status: 'completed' },
  { id: 'tx-002', truckId: 'tf-003', plateNumber: 'BG 9012 TF', driverName: 'Kagiso Banda',   stationId: 'tlokweng',    stationName: 'Tlokweng',        fuelType: 'Diesel', litresFuelled: 620, totalPula: 7_340.8, pricePerLitre: 11.84, timestamp: '2026-06-12T06:30:00Z', rfidTag: 'RFID-TF003-B', status: 'completed' },
  { id: 'tx-003', truckId: 'tf-005', plateNumber: 'BG 7890 TF', driverName: 'Boipelo Kefilwe',stationId: 'kazungula',   stationName: 'Kazungula',       fuelType: 'Diesel', litresFuelled: 750, totalPula: 8_880.0, pricePerLitre: 11.84, timestamp: '2026-06-12T05:55:00Z', rfidTag: 'RFID-TF005-C', status: 'completed' },
  { id: 'tx-004', truckId: 'tf-002', plateNumber: 'BG 5678 TF', driverName: 'Onkabetse Seheri',stationId:'gaborone-b3', stationName: 'Gaborone Block 3', fuelType: 'Diesel', litresFuelled: 900, totalPula: 10_656.0,pricePerLitre: 11.84, timestamp: '2026-06-12T09:00:00Z', rfidTag: 'RFID-TF002-D', status: 'pending' },
  { id: 'tx-005', truckId: 'tf-004', plateNumber: 'BG 3456 TF', driverName: 'Tumelo Ntshiwa', stationId: 'lobatse',     stationName: 'Lobatse',         fuelType: 'ULP95', litresFuelled: 320, totalPula: 3_904.0, pricePerLitre: 12.20, timestamp: '2026-06-11T18:22:00Z', rfidTag: 'RFID-TF004-E', status: 'completed' },
  { id: 'tx-006', truckId: 'tf-001', plateNumber: 'BG 1234 TF', driverName: 'Lesego Moremi',  stationId: 'sherwood',    stationName: 'Sherwood',        fuelType: 'Diesel', litresFuelled: 540, totalPula: 6_393.6, pricePerLitre: 11.84, timestamp: '2026-06-11T14:10:00Z', rfidTag: 'RFID-TF001-F', status: 'flagged' },
]

export const FUEL_CONSUMPTION_DATA: FuelConsumptionPoint[] = [
  { date: 'Jan', diesel: 180_000, ulp95: 42_000 },
  { date: 'Feb', diesel: 195_000, ulp95: 38_000 },
  { date: 'Mar', diesel: 210_000, ulp95: 45_000 },
  { date: 'Apr', diesel: 198_000, ulp95: 51_000 },
  { date: 'May', diesel: 225_000, ulp95: 48_000 },
  { date: 'Jun', diesel: 240_000, ulp95: 55_000 },
]

export const GROWTH_DATA = [
  { year: '2020', turnoverM: 588 },
  { year: '2021', turnoverM: 820 },
  { year: '2022', turnoverM: 1100 },
  { year: '2023', turnoverM: 1650 },
  { year: '2024', turnoverM: 2100 },
]

export const MOCK_SOCIAL_POSTS: SocialPost[] = [
  { id: 'sp-1', platform: 'linkedin', author: 'TswanaFuel', handle: '@tswanafuel', content: 'Proud to announce our Kazungula site hit a new record — 500,000 litres throughput this month. Powering SADC trade, one load at a time. 🚛⛽ #TswanaFuel #SADC #EnergyLogistics', likes: 284, comments: 34, shares: 61, timestamp: '2026-06-11T09:00:00Z', url: 'https://linkedin.com' },
  { id: 'sp-2', platform: 'x', author: 'TswanaFuel', handle: '@TswanaFuel_BW', content: 'Our Sherwood truck stop is fully operational — 24hr security, free WiFi, hot meals and border permit processing. Stop in. 📍 Sherwood, Botswana', likes: 142, comments: 18, shares: 29, timestamp: '2026-06-10T13:30:00Z', url: 'https://x.com' },
  { id: 'sp-3', platform: 'instagram', author: 'tswanafuel_bw', handle: '@tswanafuel_bw', content: 'Behind the scenes: our SHEQ training session at the Gaborone depot. Every driver, every site, every load — held to the highest safety standards. 🛡️ #SHEQ #Safety #BotswanaStrong', likes: 512, comments: 47, shares: 88, timestamp: '2026-06-09T16:00:00Z', url: 'https://instagram.com' },
  { id: 'sp-4', platform: 'linkedin', author: 'TswanaFuel', handle: '@tswanafuel', content: 'We supply bulk fuel under tender to the Botswana Defence Force, CTO and Botswana Railways — delivering reliability where it matters most. #BulkFuel #PublicSector', likes: 391, comments: 52, shares: 74, timestamp: '2026-06-08T10:00:00Z', url: 'https://linkedin.com' },
]

export const NAV_LINKS = [
  { label: 'About',      href: '/#about'    },
  { label: 'Services',   href: '/#services' },
  { label: 'Network',    href: '/#network'  },
  { label: 'Stations',   href: '/stations'  },
  { label: 'Performance',href: '/#growth'   },
] as const
